alpha: 0.9
average_attn_weights: true
batch_size: 256
beta: 0.999
bias_lr_factor: 2.0
dataset_name: RSTPReid
distributed: false
eval_period: 1
finetune: ''
gamma: 0.1
img_aug: true
img_size: !!python/tuple
- 384
- 128
lambda1_weight: 0.5
lambda2_weight: 3.5
layer_index: -1
local_rank: 0
log_period: 20
loss_names: tal+cid
lr: 1.0e-05
lr_factor: 5.0
lrscheduler: cosine
margin: 0.1
milestones: !!python/tuple
- 45
- 50
modify_k: false
momentum: 0.9
name: PPL
num_epoch: 15
num_instance: 2
num_workers: 4
only_global: true
optimizer: Adam
output_dir: ITSELF/RSTPReid/20260512_022647_ITSELF_tal+cid
power: 0.9
pretrain: ''
pretrain_choice: ViT-B/16
resume: false
resume_ckpt_file: ''
return_all: false
root_dir: data
sampler: identity
select_ratio: 0.4
stride_size: 16
target_lr: 0
tau: 0.015
temperature: 0.02
test_batch_size: 512
text_length: 77
topk_type: mean
training: true
txt_aug: true
val_dataset: test
vocab_size: 49408
warmup_epochs: 5
warmup_factor: 0.1
warmup_method: linear
weight_decay: 4.0e-05
weight_decay_bias: 0.0
