alpha: 0.9
average_attn_weights: true
batch_size: 256
beta: 0.999
bias_lr_factor: 2.0
context_module: mixer
context_pooling: mlp
dataset_name: RSTPReid
deterministic: true
deterministic_warn_only: false
distributed: false
enrich_gamma: 0.2
enrichment_space: global
enrichment_start: 1
eval_period: 1
evidence_projection: auto
evidence_token_budget: 0
extractor_mode: global
finetune: ''
finetune_clip: ''
freeze_host: true
gain_margin: 0.01
gamma: 0.1
img_aug: true
img_size: !!python/tuple
- 384
- 128
lambda1_weight: 0.5
lambda2_weight: 3.5
lambda_gain: 1.0
lambda_host: 1.0
lambda_ret: 0.5
lambda_rob: 0.1
layer_index: -1
local_rank: 0
log_period: 20
loss_names: tal+cid
lr: 1.0e-05
lr_factor: 5.0
lr_total_epochs: 60
lrscheduler: cosine
margin: 0.1
milestones: !!python/tuple
- 45
- 50
mixer_depth: 1
mixer_dim: 256
mixer_hidden_channel: 512
mixer_hidden_part: 32
mixer_hidden_rank: 128
mixer_hidden_readout: 256
modify_k: true
momentum: 0.9
name: PPL
num_epoch: 30
num_instance: 2
num_parts: 24
num_workers: 4
only_global: false
optimizer: Adam
output_dir: ITSELF/RSTPReid/20260617_050753_ITSELF_tal+cid
pnp_text_only: false
power: 0.9
pretrain: ''
pretrain_choice: ViT-B/16
recompute_interval: -1
recompute_level: epoch
residual_gate: static
residual_gate_hidden_dim: 128
resume: false
resume_ckpt_file: ''
return_all: true
robust_hard_k: 32
root_dir: data
sampler: identity
seed: 1
select_ratio: 0.4
stride_size: 16
target_enrichment: false
target_lr: 0
target_relative_cluster_method: kmeans
target_relative_num_clusters: 16
target_relative_space: host_global
tau: 0.015
temperature: 0.02
test_batch_size: 512
text_length: 77
top_m: 32
topk_type: custom
topm_rank_lambda: 0.4
topm_rank_space: hybrid_global_grab
training: true
txt_aug: true
use_freeze_indices: true
use_host_loss: false
use_target_retrieval_loss: true
use_target_robust_loss: false
use_wandb: true
val_dataset: test
vocab_size: 49408
wandb_project: transductive-itself-rstp
warmup_epochs: 5
warmup_factor: 0.1
warmup_method: linear
weight_decay: 4.0e-05
weight_decay_bias: 0.0
